### ISSUE TITLE
Please provide a tutorial / example

### ISSUE THREAD

**Issue by facontidavide** [pal-robotics/pal_statistics#2]
it would be nice if you show a complete example, since the README doesn't explain very well when and how statistics are published.

**Comment by v-lopez** [comment]
We forgot to link to the ROS wiki: http://wiki.ros.org/pal_statistics/Tutorials/Registering%20and%20publishing%20variables

Still the tutorials may need more work, please let us know what is missing.

**Comment by facontidavide** [comment]
Thanks, that is more helpful.

I have a couple of questions. As far as I understood:

1) Only plain old objects of size 8 at most can be registered.
2) you can REGISTER and UNREGISTER variables at run-time, not only at the beginnging and at the end, respectively.

Is 2) an __actual__ requirement?
If it wasn't I can imagine a dramatically more efficient way to implement this library... but that is just me I guess ;)

**Comment by v-lopez** [comment]
1. Only objects that can be casted to double, because graphite/grafana only handles doubles.
2. You can register and unregister at any point, a lot of the hacks that we're forced to do are to add this possibility. It is a requirement because there are statistics that are not known at initialization. 

For instance you may want to record metrics of navigation goals to certain waypoints, at startup you may not have the complete list of waypoints, therefore you cannot generate all registrations.

**Comment by facontidavide** [comment]
thanks
