### ISSUE TITLE
grafana howto

### ISSUE THREAD

**Issue by facontidavide** [pal-robotics/pal_statistics#3]
Hi,

I am trying to test Grafana (the "competition" if you know what I mean).

I followed the tutorial and I have a not publishing a pal_statistics topic.

The I call: 

            roslaunch pal_carbon_collector carbon_collector.launch

But I get this error 

```
   File "/home/davide.faconti/ws_plotjuggler/src/pal_statistics/pal_carbon_collector/scripts/carbon_collector_node.py", line 22, in <module>
    carbon_collector = CarbonCollector(topics, dry_run=dry_run)
  File "/home/davide.faconti/ws_plotjuggler/src/pal_statistics/pal_carbon_collector/src/pal_carbon_collector/carbon_collector.py", line 11, in __init__
    system_name=system_name, dryrun=dry_run)
  File "/usr/local/lib/python2.7/dist-packages/graphitesend/graphitesend.py", line 112, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/graphitesend/graphitesend.py", line 166, in connect
    (self.addr, error)
graphitesend.graphitesend.GraphiteSendException: unknown exception while connecting to ('localhost', 2003) - [Errno 111] Connection refused
[carbon_collector_node-1] process has died [pid 8227, exit code 1, cmd /home/davide.faconti/ws_plotjuggler/src/pal_statistics/pal_carbon_collector/scripts/carbon_collector_node.py __name:=carbon_collector_node __log:=/home/davide.faconti/.ros/log/731a9fbe-2ec3-11e9-82a4-d0577b13865c/carbon_collector_node-1.log].
log file: /home/davide.faconti/.ros/log/731a9fbe-2ec3-11e9-82a4-d0577b13865c/carbon_collector_node-1*.log
all processes on machine have died, roslaunch will exit
```

I launched the grafana server earlier with the command 

         sudo service grafana-server start
      
The GUI of grafana is visible on the default port 3000.

**Comment by jordan-palacios** [comment]
Hi,

I'm guessing you don't have the Graphite carbon demon running? This the application that reads the incoming data and saves it to the whisper database. Grafana then queries graphite and plots the data.

More info here: https://graphite.readthedocs.io/en/latest/carbon-daemons.html.

Keep in mind that instead of installing graphite from source, we use the `graphite-carbon` and `graphite-web` packages already available in the ubuntu official repositories. (They are a bit older though)
